<?php
if($_POST['show'] == true){
$emoticon  = array(
            ':shakehand2'       => '<img src="emoticons/shakehand2.gif"  alt=":shakehand2" />',
            ':ngacir2'          => '<img src="emoticons/ngacir2.gif"  alt=":ngaci2r" />',
            ':takut'            => '<img src="emoticons/takut.gif"  alt=":takut" />',
            ':recsel'           => '<img src="emoticons/recseller.gif"  alt=":recsel" />',
            ':ilovekaskus'      => '<img src="emoticons/s_sm_ilovekaskus.gif"  alt=":ilovekaskus" />',
            ':iloveindonesia'   => '<img src="emoticons/I-Luv-Indonesia.gif"  alt=":iloveindonesia" />',
            ':kiss'             => '<img src="emoticons/cewek.gif"  alt=":kiss" />',
            ':maho'             => '<img src="emoticons/s_sm_maho.gif"  alt=":maho" />',
            ':najis'            => '<img src="emoticons/najis.gif"  alt=":najis" />',
            ':nosara'           => '<img src="emoticons/nosara.gif"  alt=":nosara" />',
            ':marah'            => '<img src="emoticons/marah.gif"  alt=":marah" />',
            ':berduka'          => '<img src="emoticons/berduka.gif"  alt=":berduka" />',
            ':malu'             => '<img src="emoticons/malu.gif"  alt=":malu" />',
            ':ngakak'           => '<img src="emoticons/ngakak.gif"  alt=":ngakak" />',
            ':repost'           => '<img src="emoticons/s_sm_repost1.gif"  alt=":repost" />',
            ':repost2'          => '<img src="emoticons/s_sm_repost2.gif"  alt=":repost2" />',
            ':sup2:'            => '<img src="emoticons/sundul.gif"  alt=":sup2:" />',
            ':cendolbig'        => '<img src="emoticons/s_big_cendol.gif"  alt=":cendolbig" />',
            ':batabig'          => '<img src="emoticons/s_big_batamerah.gif"  alt=":batabig" />',
            ':cendolb'          => '<img src="emoticons/s_sm_cendol.gif"  alt=":cendolb" />',
            ':bata'             => '<img src="emoticons/s_sm_batamerah.gif"  alt=":bata" />',
            ':)b'               => '<img src="emoticons/s_sm_smile.gif"  alt=":)b" />',
            ':Yb'               => '<img src="emoticons/s_sm_peace.gif"  alt=":Yb" />',
            ':jrb:'             => '<img src="emoticons/fd_1.gif"  alt=":jrb:" />',
            ':kts:'             => '<img src="emoticons/fd_6.gif"  alt=":kts:" />',
            ':sup:'             => '<img src="emoticons/fd_5.gif"  alt=":sup:" />',
            ':kbgt:'            => '<img src="emoticons/fd_4.gif"  alt=":kbgt:" />',
            ':kacau:'           => '<img src="emoticons/fd_8.gif"  alt=":kacau:" />',
            ':bigo:'            => '<img src="emoticons/fd_3.gif"  alt=":bigo:" />',
            ':repost:'          => '<img src="emoticons/fd_7.gif"  alt=":repost:" />',
            ':cd:'              => '<img src="emoticons/fd_2.gif"  alt=":cd:" />',
            ':berbusa:'         => '<img src="emoticons/q20.gif"  alt=":berbusa:" />',
            ':breakhear'        => '<img src="emoticons/38.gif"  alt=":breakhear" />',
            ':babi:'            => '<img src="emoticons/27.gif"  alt=":babi:" />',
            ':frog:'            => '<img src="emoticons/frog.gif"  alt=":frog:" />',
            ':D'                => '<img src="emoticons/14.gif"  alt=":D" />',
            ':Peace:'           => '<img src="emoticons/005.gif"  alt=":Peace:" />',
            ':thumbdown'        => '<img src="emoticons/48.gif"  alt=":thumbdown" />',
            ':metal:'           => '<img src="emoticons/q17.gif"  alt=":metal:" />',
            ':heart:'           => '<img src="emoticons/37.gif"  alt=":heart:" />',
            ':linux2:'          => '<img src="emoticons/26.gif"  alt=":linux2:" />',
            ':afro:'            => '<img src="emoticons/kribo.gif"  alt=":afro:" />',
            ':o'                => '<img src="emoticons/07.gif"  alt=":o" />',
            ':matabelo:'        => '<img src="emoticons/004.gif"  alt=":matabelo:" />',
            ':thumbup:'         => '<img src="emoticons/47.gif"  alt=":thumbup:" />',
            ':kissmouth'        => '<img src="emoticons/36.gif"  alt=":kissmouth" />',
            ':tabrakan:'        => '<img src="emoticons/tabrakan.gif"  alt=":tabrakan:" />',
            ':genit:'           => '<img src="emoticons/q03.gif"  alt=":genit:" />',
            ':linux1:'          => '<img src="emoticons/25.gif"  alt=":linux1:" />',
            ':hi:'              => '<img src="emoticons/hi.gif"  alt=":hi:" />',
            ':('                => '<img src="emoticons/06.gif"  alt=":(" />',
            ':nohope:'          => '<img src="emoticons/q11.gif"  alt=":nohope:" />',
            ':siul:'            => '<img src="emoticons/020.gif"  alt=":siul:" />',
            ':norose:'          => '<img src="emoticons/35.gif"  alt=":norose:" />',
            ':malu:'            => '<img src="emoticons/1.gif"  alt=":malu:" />',
            ':army:'            => '<img src="emoticons/24.gif"  alt=":army:" />',
            ':fuck3:'           => '<img src="emoticons/fuck-8.gif"  alt=":fuck3:" />',
            ':)'                => '<img src="emoticons/15.gif"  alt=":)" />',
            ':Paws:'            => '<img src="emoticons/paw.gif"  alt=":Paws:" />',
            ':doctor:'          => '<img src="emoticons/18.gif"  alt=":doctor:" />',
            ':rose:'            => '<img src="emoticons/34.gif"  alt=":rose:" />',
            ':ngacir:'          => '<img src="emoticons/ngacir.gif"  alt=":ngacir:" />',
            ':confused:'        => '<img src="emoticons/7.gif"  alt=":confused:" />',
            ':angel:'           => '<img src="emoticons/017.gif"  alt=":angel:" />',
            ':fuck2:'           => '<img src="emoticons/fuck-6.gif"  alt=":fuck2:" />',
            ':kagets:'          => '<img src="emoticons/3.gif"  alt=":kagets:" />',
            ':tv:'              => '<img src="emoticons/44.gif"  alt=":tv:" />',
            ':medicine:'        => '<img src="emoticons/33.gif"  alt=":medicine:" />',
            ':fm:'              => '<img src="emoticons/smileyfm329wj.gif"  alt=":fm:" />',
            ':eek:'             => '<img src="emoticons/4.gif"  alt=":eek:" />',
            ':kissing:'         => '<img src="emoticons/014.gif"  alt=":kissing:" />',
            ':fuck:'            => '<img src="emoticons/fuck-4.gif"  alt=":fuck:" />',
            ':wowcantik'        => '<img src="emoticons/001.gif"  alt=":wowcantik" />',
            ':email:'           => '<img src="emoticons/43.gif"  alt=":email:" />',
            ':ricebowl:'        => '<img src="emoticons/32.gif"  alt=":ricebowl:" />',
            ':ck'               => '<img src="emoticons/kaskuslove.gif"  alt=":ck" />',
            ':mad:'             => '<img src="emoticons/12.gif"  alt=":mad:" />',
            ':hammer:'          => '<img src="emoticons/8.gif"  alt=":hammer:" />',
            ':flower:'          => '<img src="emoticons/e03.gif"  alt=":flower:" />',
            ':buldog:'          => '<img src="emoticons/woof.gif"  alt=":buldog:" />',
            ':clock:'           => '<img src="emoticons/42.gif"  alt=":clock:" />',
            ':coffee:'          => '<img src="emoticons/31.gif"  alt=":coffee:" />',
            ':amazed:'          => '<img src="emoticons/amazed.gif"  alt=":amazed:" />',
            ':rolleyes:'        => '<img src="emoticons/01.gif"  alt=":rolleyes:" />',
            ':sun:'             => '<img src="emoticons/008.gif"  alt=":sun:" />',
            ':rainbow:'         => '<img src="emoticons/e02.gif"  alt=":rainbow:" />',
            ':bikini:'          => '<img src="emoticons/vana-bum-vanaweb-dot-com.gif"  alt=":bikini:" />',
            ':Phone:'           => '<img src="emoticons/41.gif"  alt=":Phone:" />',
            ':baby:'            => '<img src="emoticons/30.gif"  alt=":baby:" />',
            ':gila:'            => '<img src="emoticons/crazy.gif"  alt=":gila:" />',
            ':cool:'            => '<img src="emoticons/05.gif"  alt=":cool:" />',
            ':moon:'            => '<img src="emoticons/007.gif"  alt=":moon:" />',
            ':rain:'            => '<img src="emoticons/60.gif"  alt=":rain:" />',
            ':tai:'             => '<img src="emoticons/shit-3.gif"  alt=":tai:" />',
            ':present:'         => '<img src="emoticons/40.gif"  alt=":present:" />',
            ':anjing:'          => '<img src="emoticons/29.gif"  alt=":anjing:" />',
            ':kimpoi:'          => '<img src="emoticons/smiley_couple.gif"  alt=":kimpoi:" />',
            ':p'                => '<img src="emoticons/6.gif"  alt=":p" />',
            ':think:'           => '<img src="emoticons/006.gif"  alt=":think:" />',
            ':exclamati'        => '<img src="emoticons/52.gif"  alt=":exclamati" />',
            ':Onigiri:'         => '<img src="emoticons/rice.gif"  alt=":Onigiri:" />',
            ':table:'           => '<img src="emoticons/39.gif"  alt=":table:" />',
            ':kucing:'          => '<img src="emoticons/28.gif"  alt=":kucing:" />',
            ':beer:'            => '<img src="emoticons/smiley_beer.gif"  alt=":beer:" />',
            ';)'                => '<img src="emoticons/13.gif"  alt=";)" />',
            ':shutup:'          => '<img src="emoticons/5.gif"  alt=":shutup:" />',
            ':shakehand'        => '<img src="emoticons/49.gif"  alt=":shakehand" />',
            ':bingung:'         => '<img src="emoticons/bolakbalik.gif"  alt=":bingung:" />'         
    );
    
    foreach($emoticon as $key=>$val){
        echo "<a href=\"#\" id=\"view\" title=\"".$key."\">".$val."</a>";
    }
}else{
    echo "Data tidak ditemukan";
}
?>
